### GENERAL SETTINGS ###

# Gems
gems: [jekyll-paginate]

# Site settings
title: Scala.js
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
# baseurl: ""
baseurl: ""
url: "http://scala-js.org"
exclude: ["*.iml"]
production_url : http://www.scala-js.org

# News
paginate: 6
paginate_path: "/news/page:num"
excerpt_separator: "<!--more-->"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#0077bd " #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  active: "#a44"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### VERSIONS ###
versions:
  scalaJS: 0.6.5
  scalaJSBinary: 0.6
  scalaJSDOM: 0.8.2


