### GENERAL SETTINGS ###

# Plugins
plugins: [jekyll-paginate, jekyll-assets, sass, execjs, uglifier]

# Site settings
title: Scala.js
description: "Build robust front-end web applications in Scala with Scala.js"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
# baseurl: ""
baseurl: ""
url: "https://www.scala-js.org"
exclude: ["*.iml"]
production_url: "https://www.scala-js.org"

assets:
  prefix: "/assets"
  digest: true
  sources:
    - _assets/css
    - _assets/images
    - _assets/fonts
    - _assets/js

# News
paginate: 6
paginate_path: "/news/page:num"
excerpt_separator: "<!--more-->"
future: true

# Build settings
markdown: kramdown
defaults:
  -
   scope:
     type: pages
   values:
     permalink: /:path/:basename:output_ext
  -
   scope:
     type: posts
   values:
     permalink: /:categories/:title

excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#0077bd" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  active: "#a44"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"


### VERSIONS ###
versions:
  scalaJS: 0.6.27
  scalaJSBinary: 0.6
  scalaJSDev: 1.0.0-M7
  scalaJSDevBinary: 1.0.0-M7
  scalaJSDOM: 0.9.6
